[package]
name = "get-request"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.1"
hyper = "0.11"


reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
